// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/akubi0w1/ent-sample/ent/profile"
	"github.com/akubi0w1/ent-sample/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	profileFields := schema.Profile{}.Fields()
	_ = profileFields
	// profileDescAge is the schema descriptor for age field.
	profileDescAge := profileFields[2].Descriptor()
	// profile.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	profile.AgeValidator = profileDescAge.Validators[0].(func(int) error)
}
